
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("09f7c709-5be3-458d-bc12-0dd6acad3cb1")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class NorthwindEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=NorthwindEntities", "NorthwindEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new NorthwindEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "NorthwindEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new NorthwindEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "NorthwindEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Products() As ObjectSet(Of Product)
        Get
            If (_Products Is Nothing) Then
                _Products = MyBase.CreateObjectSet(Of Product)("Products")
            End If
            Return _Products
        End Get
    End Property

    Private _Products As ObjectSet(Of Product)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducts(ByVal product As Product)
        MyBase.AddObject("Products", product)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Product object.
    ''' </summary>
    ''' <param name="productID">Initial value of the ProductID property.</param>
    ''' <param name="productName">Initial value of the ProductName property.</param>
    ''' <param name="discontinued">Initial value of the Discontinued property.</param>
    Public Shared Function CreateProduct(productID As Global.System.Int32, productName As Global.System.String, discontinued As Global.System.Boolean) As Product
        Dim product as Product = New Product
        product.ProductID = productID
        product.ProductName = productName
        product.Discontinued = discontinued
        Return product
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductID() As Global.System.Int32
        Get
            Return _ProductID
        End Get
        Set
            If (_ProductID <> Value) Then
                OnProductIDChanging(value)
                ReportPropertyChanging("ProductID")
                _ProductID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProductID")
                OnProductIDChanged()
            End If
        End Set
    End Property

    Private _ProductID As Global.System.Int32
    Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProductIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductName() As Global.System.String
        Get
            Return _ProductName
        End Get
        Set
            OnProductNameChanging(value)
            ReportPropertyChanging("ProductName")
            _ProductName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ProductName")
            OnProductNameChanged()
        End Set
    End Property

    Private _ProductName As Global.System.String
    Private Partial Sub OnProductNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SupplierID() As Nullable(Of Global.System.Int32)
        Get
            Return _SupplierID
        End Get
        Set
            OnSupplierIDChanging(value)
            ReportPropertyChanging("SupplierID")
            _SupplierID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SupplierID")
            OnSupplierIDChanged()
        End Set
    End Property

    Private _SupplierID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSupplierIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSupplierIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryID() As Nullable(Of Global.System.Int32)
        Get
            Return _CategoryID
        End Get
        Set
            OnCategoryIDChanging(value)
            ReportPropertyChanging("CategoryID")
            _CategoryID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CategoryID")
            OnCategoryIDChanged()
        End Set
    End Property

    Private _CategoryID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCategoryIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCategoryIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property QuantityPerUnit() As Global.System.String
        Get
            Return _QuantityPerUnit
        End Get
        Set
            OnQuantityPerUnitChanging(value)
            ReportPropertyChanging("QuantityPerUnit")
            _QuantityPerUnit = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("QuantityPerUnit")
            OnQuantityPerUnitChanged()
        End Set
    End Property

    Private _QuantityPerUnit As Global.System.String
    Private Partial Sub OnQuantityPerUnitChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnQuantityPerUnitChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UnitPrice() As Nullable(Of Global.System.Decimal)
        Get
            Return _UnitPrice
        End Get
        Set
            OnUnitPriceChanging(value)
            ReportPropertyChanging("UnitPrice")
            _UnitPrice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UnitPrice")
            OnUnitPriceChanged()
        End Set
    End Property

    Private _UnitPrice As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnUnitPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnUnitPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UnitsInStock() As Nullable(Of Global.System.Int16)
        Get
            Return _UnitsInStock
        End Get
        Set
            OnUnitsInStockChanging(value)
            ReportPropertyChanging("UnitsInStock")
            _UnitsInStock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UnitsInStock")
            OnUnitsInStockChanged()
        End Set
    End Property

    Private _UnitsInStock As Nullable(Of Global.System.Int16)
    Private Partial Sub OnUnitsInStockChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnUnitsInStockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UnitsOnOrder() As Nullable(Of Global.System.Int16)
        Get
            Return _UnitsOnOrder
        End Get
        Set
            OnUnitsOnOrderChanging(value)
            ReportPropertyChanging("UnitsOnOrder")
            _UnitsOnOrder = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UnitsOnOrder")
            OnUnitsOnOrderChanged()
        End Set
    End Property

    Private _UnitsOnOrder As Nullable(Of Global.System.Int16)
    Private Partial Sub OnUnitsOnOrderChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnUnitsOnOrderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReorderLevel() As Nullable(Of Global.System.Int16)
        Get
            Return _ReorderLevel
        End Get
        Set
            OnReorderLevelChanging(value)
            ReportPropertyChanging("ReorderLevel")
            _ReorderLevel = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ReorderLevel")
            OnReorderLevelChanged()
        End Set
    End Property

    Private _ReorderLevel As Nullable(Of Global.System.Int16)
    Private Partial Sub OnReorderLevelChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnReorderLevelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Discontinued() As Global.System.Boolean
        Get
            Return _Discontinued
        End Get
        Set
            OnDiscontinuedChanging(value)
            ReportPropertyChanging("Discontinued")
            _Discontinued = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Discontinued")
            OnDiscontinuedChanged()
        End Set
    End Property

    Private _Discontinued As Global.System.Boolean
    Private Partial Sub OnDiscontinuedChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnDiscontinuedChanged()
    End Sub

    #End Region
End Class

#End Region

